# A simplified configuration for debugging the 404 error.

[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# This header is essential for embedding your site in the Squarespace iframe.
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "ALLOWALL"