import { supabase } from '@/integrations/supabase/client';
import { BusinessType } from '@/types/businessTypes';
import { EnhancedAnalysis } from '@/types/dataAnalysis';

export interface EmailOptions {
  recipient: string;
  businessName: string;
  businessType: BusinessType;
  subject?: string;
  includeAttachments?: boolean;
}

export interface EmailTemplate {
  subject: string;
  html: string;
}

export async function sendWeeklySummary(options: EmailOptions, analysisData: EnhancedAnalysis) {
  try {
    const template = generateWeeklySummaryTemplate(options, analysisData);
    
    const { data: result, error } = await supabase.functions.invoke('send-email-summary', {
      body: {
        recipient: options.recipient,
        subject: template.subject,
        html: template.html,
        includeAttachments: options.includeAttachments || false,
      }
    });

    if (error) {
      console.error('Email notification error:', error);
      throw new Error(`Failed to send email: ${error.message}`);
    }

    return result;
  } catch (err) {
    console.error('Email service error:', err);
    throw err;
  }
}

export async function sendUrgentAlert(options: EmailOptions, issue: any) {
  try {
    const subject = `⚠️ URGENT: Issue detected for ${options.businessName}`;
    
    const html = `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
        <div style="background-color: #FF5252; color: white; padding: 15px; text-align: center;">
          <h1 style="margin: 0;">Urgent Alert</h1>
        </div>
        <div style="padding: 20px; border: 1px solid #ddd; border-top: none;">
          <p>An urgent issue has been detected for <strong>${options.businessName}</strong>:</p>
          <div style="background-color: #FFF8E1; padding: 15px; border-left: 4px solid #FFC107; margin: 15px 0;">
            <h3 style="margin-top: 0;">${issue.title}</h3>
            <p>${issue.description}</p>
            <p><strong>Impact:</strong> ${issue.impact}</p>
          </div>
          <div style="margin-top: 20px;">
            <h3>Recommended Actions:</h3>
            <ul>
              ${issue.recommendations.map((rec: string) => `<li>${rec}</li>`).join('')}
            </ul>
          </div>
          <div style="margin-top: 30px; padding-top: 20px; border-top: 1px solid #eee; font-size: 12px; color: #666;">
            <p>This alert was generated by Star-Gazer Analysis. Log in to your dashboard for more details.</p>
          </div>
        </div>
      </div>
    `;
    
    const { data: result, error } = await supabase.functions.invoke('send-email-summary', {
      body: {
        recipient: options.recipient,
        subject,
        html,
        includeAttachments: false,
      }
    });

    if (error) {
      console.error('Urgent email notification error:', error);
      throw new Error(`Failed to send urgent alert: ${error.message}`);
    }

    return result;
  } catch (err) {
    console.error('Email service error:', err);
    throw err;
  }
}

export async function sendMonthlyPerformance(options: EmailOptions, analysisData: EnhancedAnalysis) {
  try {
    // Generate a more comprehensive monthly performance report
    const template = generateMonthlyReportTemplate(options, analysisData);
    
    const { data: result, error } = await supabase.functions.invoke('send-email-summary', {
      body: {
        recipient: options.recipient,
        subject: template.subject,
        html: template.html,
        includeAttachments: options.includeAttachments || true, // Default to including attachments for monthly reports
      }
    });

    if (error) {
      console.error('Monthly report email error:', error);
      throw new Error(`Failed to send monthly report: ${error.message}`);
    }

    return result;
  } catch (err) {
    console.error('Email service error:', err);
    throw err;
  }
}

function generateWeeklySummaryTemplate(options: EmailOptions, data: EnhancedAnalysis): EmailTemplate {
  const subject = options.subject || `Weekly Review Summary - ${options.businessName}`;
  
  // Extract key metrics for the summary
  const topClusters = data.reviewClusters
    .sort((a, b) => b.reviewCount - a.reviewCount)
    .slice(0, 3);
  
  const latestTrend = data.historicalTrends[0]; // Assuming the first trend is the most relevant
  
  // Build the HTML template
  const html = `
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
      <div style="background-color: #4A6FFF; color: white; padding: 15px; text-align: center;">
        <h1 style="margin: 0;">Weekly Review Summary</h1>
        <p style="margin: 5px 0 0 0;">${options.businessName}</p>
      </div>
      
      <div style="padding: 20px; border: 1px solid #ddd; border-top: none;">
        <h2>Performance Overview</h2>
        
        <div style="display: flex; justify-content: space-between; margin-bottom: 20px;">
          <div style="flex: 1; padding: 10px; background-color: #f5f5f5; margin-right: 10px; text-align: center;">
            <h3 style="margin-top: 0;">Average Rating</h3>
            <p style="font-size: 24px; font-weight: bold;">${latestTrend?.data[latestTrend.data.length - 1].value.toFixed(1) || 'N/A'}</p>
          </div>
          
          <div style="flex: 1; padding: 10px; background-color: #f5f5f5; margin-left: 10px; text-align: center;">
            <h3 style="margin-top: 0;">Trend</h3>
            <p style="font-size: 24px; font-weight: bold; color: ${
              latestTrend?.trend === 'improving' ? 'green' : 
              latestTrend?.trend === 'declining' ? 'red' : 
              'grey'
            }">
              ${latestTrend?.trend.charAt(0).toUpperCase() + latestTrend?.trend.slice(1) || 'N/A'}
            </p>
          </div>
        </div>
        
        <h2>Key Insights</h2>
        <ul>
          ${data.insights.keyFindings.map(finding => `<li>${finding}</li>`).join('')}
        </ul>
        
        <h2>Top Review Clusters</h2>
        <table style="width: 100%; border-collapse: collapse; margin-top: 15px;">
          <tr style="background-color: #f5f5f5;">
            <th style="padding: 10px; text-align: left; border: 1px solid #ddd;">Cluster</th>
            <th style="padding: 10px; text-align: center; border: 1px solid #ddd;">Reviews</th>
            <th style="padding: 10px; text-align: center; border: 1px solid #ddd;">Rating</th>
          </tr>
          ${topClusters.map(cluster => `
            <tr>
              <td style="padding: 10px; border: 1px solid #ddd;">${cluster.name}</td>
              <td style="padding: 10px; text-align: center; border: 1px solid #ddd;">${cluster.reviewCount}</td>
              <td style="padding: 10px; text-align: center; border: 1px solid #ddd;">${cluster.averageRating.toFixed(1)}</td>
            </tr>
          `).join('')}
        </table>
        
        <div style="margin-top: 30px; text-align: center;">
          <a href="#" style="display: inline-block; padding: 10px 20px; background-color: #4A6FFF; color: white; text-decoration: none; border-radius: 4px;">
            View Full Report
          </a>
        </div>
        
        <div style="margin-top: 30px; padding-top: 20px; border-top: 1px solid #eee; font-size: 12px; color: #666; text-align: center;">
          <p>This report was generated by Star-Gazer Analysis.</p>
        </div>
      </div>
    </div>
  `;
  
  return { subject, html };
}

function generateMonthlyReportTemplate(options: EmailOptions, data: EnhancedAnalysis): EmailTemplate {
  const subject = options.subject || `Monthly Performance Report - ${options.businessName}`;
  
  // Extract opportunities and risks for the report
  const opportunities = data.insights.opportunities;
  const risks = data.insights.risks;
  
  // Get seasonal pattern if available
  const currentSeason = data.seasonalAnalysis.find(s => s.season !== 'custom') || data.seasonalAnalysis[0];
  
  // Build the HTML template for a more comprehensive monthly report
  const html = `
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
      <div style="background-color: #4A6FFF; color: white; padding: 20px; text-align: center;">
        <h1 style="margin: 0;">Monthly Performance Report</h1>
        <p style="margin: 5px 0 0 0;">${options.businessName} | ${new Date().toLocaleDateString('en-US', { month: 'long', year: 'numeric' })}</p>
      </div>
      
      <div style="padding: 30px; border: 1px solid #ddd; border-top: none;">
        <div style="background-color: #F8F9FA; padding: 20px; margin-bottom: 30px;">
          <h2 style="margin-top: 0; color: #333;">Executive Summary</h2>
          <p>This report provides a comprehensive overview of your business's performance based on customer reviews over the past month.</p>
          <div style="display: flex; justify-content: space-between; margin-top: 20px;">
            <div style="flex: 1; text-align: center; padding: 15px;">
              <p style="font-size: 14px; color: #666; margin-bottom: 5px;">Total Reviews</p>
              <p style="font-size: 28px; font-weight: bold; margin: 0;">
                ${data.reviewClusters.reduce((sum, cluster) => sum + cluster.reviewCount, 0)}
              </p>
            </div>
            <div style="flex: 1; text-align: center; padding: 15px;">
              <p style="font-size: 14px; color: #666; margin-bottom: 5px;">Avg Rating</p>
              <p style="font-size: 28px; font-weight: bold; margin: 0;">
                ${(data.reviewClusters.reduce((sum, cluster) => sum + (cluster.averageRating * cluster.reviewCount), 0) / 
                data.reviewClusters.reduce((sum, cluster) => sum + cluster.reviewCount, 0)).toFixed(1)}
              </p>
            </div>
            <div style="flex: 1; text-align: center; padding: 15px;">
              <p style="font-size: 14px; color: #666; margin-bottom: 5px;">Most Common</p>
              <p style="font-size: 18px; font-weight: bold; margin: 0;">
                ${data.reviewClusters.sort((a, b) => b.reviewCount - a.reviewCount)[0]?.name || 'N/A'}
              </p>
            </div>
          </div>
        </div>
        
        <div style="margin-bottom: 30px;">
          <h2 style="color: #333; border-bottom: 2px solid #eee; padding-bottom: 10px;">Key Findings</h2>
          <ul style="padding-left: 20px; line-height: 1.6;">
            ${data.insights.keyFindings.map(finding => `<li style="margin-bottom: 10px;">${finding}</li>`).join('')}
          </ul>
        </div>
        
        <div style="display: flex; gap: 20px; margin-bottom: 30px;">
          <div style="flex: 1; background-color: #E8F5E9; padding: 20px; border-radius: 4px;">
            <h3 style="margin-top: 0; color: #2E7D32;">Opportunities</h3>
            <ul style="padding-left: 20px; margin-bottom: 0;">
              ${opportunities.map(op => `<li style="margin-bottom: 8px;">${op}</li>`).join('')}
            </ul>
          </div>
          
          <div style="flex: 1; background-color: #FFEBEE; padding: 20px; border-radius: 4px;">
            <h3 style="margin-top: 0; color: #C62828;">Risks</h3>
            <ul style="padding-left: 20px; margin-bottom: 0;">
              ${risks.map(risk => `<li style="margin-bottom: 8px;">${risk}</li>`).join('')}
            </ul>
          </div>
        </div>
        
        ${currentSeason ? `
          <div style="margin-bottom: 30px;">
            <h2 style="color: #333; border-bottom: 2px solid #eee; padding-bottom: 10px;">Seasonal Insights: ${currentSeason.name}</h2>
            <p>${currentSeason.dateRange.start} to ${currentSeason.dateRange.end}</p>
            
            <div style="margin-top: 15px;">
              <h4 style="margin-bottom: 10px;">Top Seasonal Themes</h4>
              <div style="display: flex; flex-wrap: wrap; gap: 8px;">
                ${currentSeason.metrics.topThemes.map(theme => 
                  `<span style="background-color: #E3F2FD; padding: 6px 12px; border-radius: 20px; font-size: 14px;">${theme}</span>`
                ).join('')}
              </div>
            </div>
            
            <div style="margin-top: 20px;">
              <h4 style="margin-bottom: 10px;">Seasonal Recommendations</h4>
              <ul style="padding-left: 20px;">
                ${currentSeason.recommendations.map(rec => `<li style="margin-bottom: 8px;">${rec}</li>`).join('')}
              </ul>
            </div>
          </div>
        ` : ''}
        
        <div style="text-align: center; margin-top: 40px;">
          <a href="#" style="display: inline-block; padding: 12px 24px; background-color: #4A6FFF; color: white; text-decoration: none; border-radius: 4px; font-weight: bold;">
            View Detailed Dashboard
          </a>
        </div>
        
        <div style="margin-top: 40px; padding-top: 20px; border-top: 1px solid #eee; font-size: 12px; color: #666; text-align: center;">
          <p>This report was generated by Star-Gazer Analysis. For questions or support, please contact support@star-gazer.com</p>
        </div>
      </div>
    </div>
  `;
  
  return { subject, html };
}
